## Preprocessing

In [32]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [33]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df= application_df.drop(['EIN', 'NAME'],1)
application_df

<ipython-input-33-90a16ca4009f>:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  application_df= application_df.drop(['EIN', 'NAME'],1)

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [34]:
# Determine the number of unique values in each column.
counts = application_df.nunique()
counts

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [35]:
# Look at APPLICATION_TYPE value counts for binning
application_counts = application_df.APPLICATION_TYPE.value_counts()
application_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [36]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_counts[application_counts < 520].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [37]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df.CLASSIFICATION.value_counts()
classification_counts.head(15)

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
Name: CLASSIFICATION, dtype: int64

In [38]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_counts[classification_counts < 1800].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [39]:
# Convert categorical data to numeric with `pd.get_dummies`
numeric_df = pd.get_dummies(application_df)
numeric_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [40]:
# Split our preprocessed data into our features and target arrays
y = numeric_df["IS_SUCCESSFUL"].values
X = numeric_df.drop(["IS_SUCCESSFUL"],1).values
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

<ipython-input-40-b7ee9ab9172b>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  X = numeric_df.drop(["IS_SUCCESSFUL"],1).values

In [41]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [42]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#original 120,90

number_input_features = len(X_train[0])
hidden_nodes_layer1 =  27
hidden_nodes_layer2 = 18
hidden_nodes_layer3 = 36

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="LeakyReLU")
)
# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="LeakyReLU"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="LeakyReLU"))




# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_4 (Dense)             (None, 27)                1188

 dense_5 (Dense)             (None, 18)                504

 dense_6 (Dense)             (None, 36)                684

 dense_7 (Dense)             (None, 1)                 37

=================================================================
Total params: 2,413
Trainable params: 2,413
Non-trainable params: 0
_________________________________________________________________

In [43]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [44]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.5779 - accuracy: 0.7134
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5598 - accuracy: 0.7236
Epoch 3/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5563 - accuracy: 0.7265
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5545 - accuracy: 0.7283
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5532 - accuracy: 0.7293
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5524 - accuracy: 0.7297
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5513 - accuracy: 0.7308
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5507 - accuracy: 0.7304
Epoch 9/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5498 - accuracy: 0.7307
Epoch 10/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5498 - accuracy: 0.7309
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5491 - accuracy: 0.7316
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5489 - accuracy: 0.7304
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5484 - accuracy: 0.7326
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5479 - accuracy: 0.7332
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5475 - accuracy: 0.7327
Epoch 16/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5479 - accuracy: 0.7317
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5475 - accuracy: 0.7319
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5473 - accuracy: 0.7318
Epoch 19/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5471 - accuracy: 0.7317
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5465 - accuracy: 0.7328
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5463 - accuracy: 0.7328
Epoch 22/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5467 - accuracy: 0.7326
Epoch 23/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5460 - accuracy: 0.7321
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5463 - accuracy: 0.7320
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5461 - accuracy: 0.7316
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5460 - accuracy: 0.7307
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5459 - accuracy: 0.7323
Epoch 28/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5454 - accuracy: 0.7329
Epoch 29/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5456 - accuracy: 0.7328
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5453 - accuracy: 0.7324
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5453 - accuracy: 0.7334
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5451 - accuracy: 0.7338
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5451 - accuracy: 0.7332
Epoch 34/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5443 - accuracy: 0.7346
Epoch 35/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5443 - accuracy: 0.7338
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5449 - accuracy: 0.7334
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5441 - accuracy: 0.7345
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5446 - accuracy: 0.7327
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5443 - accuracy: 0.7347
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5443 - accuracy: 0.7341
Epoch 41/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5436 - accuracy: 0.7333
Epoch 42/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5439 - accuracy: 0.7353
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5438 - accuracy: 0.7343
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5433 - accuracy: 0.7343
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5434 - accuracy: 0.7345
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5434 - accuracy: 0.7347
Epoch 47/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5435 - accuracy: 0.7355
Epoch 48/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5436 - accuracy: 0.7336
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5436 - accuracy: 0.7341
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5430 - accuracy: 0.7353
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5434 - accuracy: 0.7350
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7334
Epoch 53/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5426 - accuracy: 0.7367
Epoch 54/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5427 - accuracy: 0.7354
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5424 - accuracy: 0.7356
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5429 - accuracy: 0.7343
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5421 - accuracy: 0.7362
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7352
Epoch 59/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5424 - accuracy: 0.7349
Epoch 60/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5424 - accuracy: 0.7350
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5423 - accuracy: 0.7346
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7353
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7365
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5418 - accuracy: 0.7358
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5417 - accuracy: 0.7359
Epoch 66/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5425 - accuracy: 0.7349
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7356
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5420 - accuracy: 0.7357
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7362
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7352
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7367
Epoch 72/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5415 - accuracy: 0.7362
Epoch 73/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5414 - accuracy: 0.7353
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7367
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7352
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7367
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7354
Epoch 78/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5410 - accuracy: 0.7359
Epoch 79/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5411 - accuracy: 0.7358
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7360
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7362
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7368
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7351
Epoch 84/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5410 - accuracy: 0.7369
Epoch 85/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5407 - accuracy: 0.7357
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7369
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7374
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7358
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7355
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7368
Epoch 91/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5405 - accuracy: 0.7360
Epoch 92/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5402 - accuracy: 0.7378
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7372
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5400 - accuracy: 0.7369
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7363
Epoch 96/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5402 - accuracy: 0.7368
Epoch 97/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5404 - accuracy: 0.7355
Epoch 98/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5405 - accuracy: 0.7357
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5400 - accuracy: 0.7363
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7372

In [45]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5553 - accuracy: 0.7327 - 551ms/epoch - 2ms/step
Loss: 0.5553073883056641, Accuracy: 0.7327113747596741

In [46]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity_Optimization.h5')

from google.colab import files

nn.save('AlphabetSoupCharity_Optimization.h5')
files.download('AlphabetSoupCharity_Optimization.h5')